### PR TITLE
sophia

### PR DESCRIPTION
**Pull request by sampita**
One more for Sophia! She'd like to be marked as hired too (data analytics job)!

### CODE REVIEW

**Review by laurenriddle — APPROVED** [review]
Yay, Sophia!! 🎉🎉

Thank you for updating these, Sam!!

**Comment by sampita** [comment]
> Yay, Sophia!! 🎉🎉
> 
> Thank you for updating these, Sam!!

@laurenriddle  What do I need to do after merging everything into deployed_master again? It's been sooooo long!

**Comment by laurenriddle** [comment]
@sampita haha! you will need to checkout deployed master, pull everything down, and then while you are on that branch run `npm run deploy`

**Comment by sampita** [comment]
> @sampita haha! you will need to checkout deployed master, pull everything down, and then while you are on that branch run `npm run deploy`

Lol oh yes THAT was the command. Thanks!! 🙂

**Pull request merged**
